apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gdg-attendees-prod

namePrefix: prod-

resources:
  - ../../

patchesStrategicMerge:
  - deployment-patch.yaml
  - ingress-patch.yaml
  - tls-patch.yaml

images:
  - name: gdg-attendees-api
    newTag: v1.0.0
  - name: attendees-app
    newTag: v1.0.0

replicas:
  - name: api-deployment
    count: 3
  - name: web-deployment
    count: 2
