apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gdg-attendees-dev

namePrefix: dev-

resources:
  - ../../

patchesStrategicMerge:
  - deployment-patch.yaml
  - ingress-patch.yaml

images:
  - name: gdg-attendees-api
    newTag: dev-latest
  - name: attendees-app
    newTag: dev-latest

replicas:
  - name: api-deployment
    count: 1
  - name: web-deployment
    count: 1
