version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - PORT=3000
      - ENV=development
    volumes:
      - ./api:/app
      - /app/tmp
    networks:
      - gdg-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    volumes:
      - ./web:/app
      - /app/node_modules
    networks:
      - gdg-network
    depends_on:
      - api
    restart: unless-stopped

networks:
  gdg-network:
    driver: bridge
