apiVersion: v1
kind: ServiceMonitor
metadata:
  name: api-servicemonitor
  namespace: gdg-attendees
  labels:
    app.kubernetes.io/name: gdg-attendees
    app.kubernetes.io/component: api
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gdg-attendees
      app.kubernetes.io/component: api
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
---
apiVersion: v1
kind: ServiceMonitor
metadata:
  name: web-servicemonitor
  namespace: gdg-attendees
  labels:
    app.kubernetes.io/name: gdg-attendees
    app.kubernetes.io/component: web
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gdg-attendees
      app.kubernetes.io/component: web
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
