apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: gdg-attendees
  labels:
    app.kubernetes.io/name: gdg-attendees
    app.kubernetes.io/component: api
type: Opaque
data:
  # Base64 encoded secrets (replace with actual values)
  # To encode: echo -n "your-secret" | base64
  DB_USERNAME: dXNlcg==  # user
  DB_PASSWORD: cGFzc3dvcmQ=  # password
  JWT_SECRET: eW91ci1qd3Qtc2VjcmV0LWtleQ==  # your-jwt-secret-key
  API_KEY: eW91ci1hcGkta2V5  # your-api-key
